# MPLAB IDE generated this makefile for use with GNU make.
# Project: Proy_14.mcp
# Date: Sat May 02 00:22:29 2015

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

Proy_14.cof : INT_RB_TECLADO.o
	$(CC) /p16F88 "INT_RB_TECLADO.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"Proy_14.cof" /M"Proy_14.map" /W

INT_RB_TECLADO.o : INT_RB_TECLADO.asm ../../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F88.inc
	$(AS) /q /p16F88 "INT_RB_TECLADO.asm" /l"INT_RB_TECLADO.lst" /e"INT_RB_TECLADO.err" /o"INT_RB_TECLADO.o" /d__DEBUG=1

clean : 
	$(CC) "INT_RB_TECLADO.o" "INT_RB_TECLADO.err" "INT_RB_TECLADO.lst" "Proy_14.cof" "Proy_14.hex"

